spring:
  profiles:
    active:
      - dev
---
server:
 port: 8002
mybatis:
 mapper-locations:
 - classpath:mapping/*.xml
spring:
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
   driverClassName: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
   url: jdbc:mysql://127.0.0.1:3306/microservice-product?serverTimezone=GMT%2B8
   username: root # 数据库用户名
   password: root # 数据库连接密码
 application:
   name: product-service
 profiles: dev

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka1:6001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

info:
  app.name: cloud-provider-product
  company.name: ppl
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

management:
  endpoints:
    web:
      exposure:
        include: '*'




