server:
  port: 1115
spring:
  application:
    name: feign-consumer
eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/